### ISSUE TITLE
L'eredità

### ISSUE THREAD

**Issue by dardo82** [nightflyer73/plugin.video.raitv#13]
Why doesn't it works?

**Comment by nightflyer73** [comment]
It doesn't work on rai.tv website too. It is an upstream problem. They don't provide an URL for the programme.

**Comment by dardo82** [comment]
This is false.
For example here is the page about the first episode of the new season:
http://www.rai.tv/dl/RaiTV/programmi/media/ContentItem-4c172ac8-77d6-4b08-955d-df311147d765.html
This instead is the URL of the MP4:
http://creativemedia3.rai.it/podcastcdn/raiuno/Eredita/Eredita_EP_Puntate/4491419_1800.mp4
So double check it.
I don't know how the script works, otherwise I would have fixed it by now... 
If you'd like to explain it, even briefly, I could be of better help in the maintenance of the same. 
I have have used [this site](http://www.pasty.link) to get the URL of the MP4. 
Anyway  the RAI.TV website works, even on my Nexus7, it's just not optimized for such screens.

**Comment by nightflyer73** [comment]
Can you please moderate you language and tell me the steps you do to access "l'eredità" using this Kodi addon? Can you please attach a log file?

I do "Programmi on demand" -> "L" -> "L'Eredità 2015-2016".

This is the same way you can do on rai.tv web site (please try!) and as you can see the link there is missing (try to compare it with the previous one "L'Eredità 2014-2015").

The addon works in the same way. If you cannot browse rai.tv web site, neither the addon can.

**Comment by dardo82** [comment]
My language is already even to much moderated and I don't like your tone. 
Anyway you are right that following that procedure you can't find any video. 
That just means that unsurprisingly the RAI site is a bit broken in that part. 
I just went to the subdomain of the TV show to find all the episodes listed. 
http://www.leredita.rai.it/
Again, if you EXPLAIN how it works, maybe I can HELP fixing the script, ok?

**Comment by nightflyer73** [comment]
You came here crying that this plugin was broken and you didn't even say how to reproduce this issue. I told you what the problem was and you started accusing me of lying and to double check the issue. At the end you told me you don't like my tone and that your language is already too much moderate even though it seems I was right about the description of the problem. 

Please remember that you had this plugin for free (both as in beer and as in freedom). Nobody paid me for developing or even supporting this plugin. It is a gift to the Kodi community. Therefore frankly your attitude is really out of line.

Rai.tv website has a problem. More precisely the metadata in http://www.rai.tv/dl/ricerca_programmi/rai_tv-ricerca-programmi.json are sometimes broken. This is the part for "L'Eredità":

{"title":"L'Eredità  2015-2016","index":"l","linkDemand":"","nascosto":"false","sottotitolato":"false","integrale":"true","tematiche":[],"editore":"RaiUno"},

As you can see there is no value for the linkDemand item. 

I cannot do nothing about that. The only thing I can do is to hope they will solve the issue soon. 

If you want to know how this plugin works, the source code is available in this same repository.

**Comment by dardo82** [comment]
HAVE YOU EVER HEARD OF DOCUMENTATION?
